site_name: Catalogue composants BP/BTS CIEL
site_description: Tutos et exemples Arduino (PlatformIO) pour composants électroniques

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

plugins:
  - search
  - include-markdown:
      rewrite_relative_urls: true

repo_url: https://github.com/clementponssard/CIEL_composants_electroniques
repo_name: CIEL_composants_electroniques

nav:
  - Accueil: index.md
  - Parcours:
    - Bac Pro: parcours/bacpro.md
    - BTS: parcours/bts.md
  - Composants:
    - DHT22: composants/dht22/index.md
    - MPU6050:
        - Aperçu: composants/mpu6050/index.md
        - Tuto 1: composants/mpu6050/tuto-1-debuter.md
        - Tuto 2: composants/mpu6050/tuto-2-approfondir.md
  - Contribuer: contribute.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
      toc_depth: 2
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/clementponssard/CIEL_composants_electroniques
