name: Deploy Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and plugins
        run: pip install mkdocs-material mkdocs-include-markdown-plugin

      - name: Build site
        run: mkdocs build

      - name: Copy component images into site
        shell: bash
        run: |
          shopt -s globstar nullglob
          for p in composants/**/images/*; do
            [ -f "$p" ] || continue
            mkdir -p "site/$(dirname "$p")"
            cp "$p" "site/$p"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
